export const LIST_FORCHAT_REQUEST = 'LIST_FORCHAT_REQUEST';
export const LIST_FORCHAT_SUCCESS = 'LIST_FORCHAT_SUCCESS';
export const LIST_FORCHAT_FAIL = 'LIST_FORCHAT_FAIL';


export const SINGLE_TEXT_REQUEST = 'SINGLE_TEXT_REQUEST';
export const SINGLE_TEXT_SUCCESS = 'SINGLE_TEXT_SUCCESS';
export const SINGLE_TEXT_FAIL = 'SINGLE_TEXT_FAIL';