export const LIKE_REQUEST = 'LIKE_REQUEST';
export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const LIKE_FAIL = 'LIKE_FAIL';
export const LIKE_RESET = 'LIKE_RESET';


export const GET_LIKES_REQUEST = 'GET_LIKES_REQUEST';
export const GET_LIKES_SUCCESS = 'GET_LIKES_SUCCESS';
export const GET_LIKES_FAIL = 'GET_LIKES_FAIL';
export const GET_LIKES_RESET = 'GET_LIKES_RESET';